services:
  webserver:
    build: .  # 현재 디렉토리에서 Dockerfile을 빌드
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ecommerce-network    
    volumes:
      - ./conf.d:/etc/nginx/conf.d  # nginx.conf 폴더를 마운트
      - ./nginx.conf:/etc/nginx/nginx.conf  # nginx.conf 폴더를 마운트

networks:
  ecommerce-network:
    external: true
